### ISSUE TITLE
[BUG] Sends player kill messages when killing entity

### ISSUE THREAD

**Issue by Jappy007** [ByMartrixx/player-events#5] opened 2021-03-23 20:53 UTC
The server sends the message of killing a person when killing entity

**How to re-create:** 

1. create server with the 2.0.0 version
2. take spawn egg(you choose wich)
3. kill the animal you spawn

**Expected behavior:**
It should send the Killed entity message

![2021-03-23_21 47 59](https://user-images.githubusercontent.com/76853484/112216272-9b2a9280-8c21-11eb-82f3-ac387018b644.png)
Config File:
![image](https://user-images.githubusercontent.com/76853484/112216646-0bd1af00-8c22-11eb-8a7c-8dfcf0940cfd.png)

**Comment by IotaBread** [comment] 2021-03-23 22:34
Thanks for letting me know! I'll look into this later

**Comment by Jappy007** [comment] 2021-03-24 08:07
Thank you kind sir 👌

**Comment by IotaBread** [comment] 2021-03-25 00:49
I think I've found the cause of this
https://github.com/ByMartrixx/player-events/blob/8bf9c24d2e25af80a30c85f2bf030940b5c60586/src/main/java/io/github/bymartrixx/playerevents/config/PlayerEventsConfig.java#L138-L139

It literally runs the `killPlayer` actions on the `killEntity` event. I've fixed it and will be in the next release

**Comment by Jappy007** [comment] 2021-03-25 09:59
Awesome thank you for fixing it so fast :-)

**Comment by IotaBread** [comment] 2021-03-25 22:57
Just released 2.1.0 Beta 1

**Closed as completed by IotaBread** 2021-03-25 22:57 UTC
Labels: bug
